spring.application.name=Gateway

server.port=5555


# Register this service with Eureka
eureka.client.register-with-eureka=true

# Fetch registry from Eureka
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8080/eureka/


# ===== Spring Cloud Gateway Route =====
spring.cloud.gateway.server.webflux.routes[0].id=auth-service-app
spring.cloud.gateway.server.webflux.routes[0].uri=lb://SPRING-SECURITY
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**



spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1
spring.main.web-application-type=reactive