spring.application.name=Gateway
server.port=5555

# Eureka config
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8080/eureka/

# ===== Route 1 (Auth Service) =====
spring.cloud.gateway.server.webflux.routes[0].id=auth-service-app
spring.cloud.gateway.server.webflux.routes[0].uri=lb://SPRING-SECURITY
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1

# ===== Route 2 (Microservice 1) =====
spring.cloud.gateway.server.webflux.routes[1].id=micro1-service-app
spring.cloud.gateway.server.webflux.routes[1].uri=lb://MICROSERVICE1
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/micro1/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=1

# ===== Route 3 (Property Services) =====
spring.cloud.gateway.server.webflux.routes[2].id=property-service-app
spring.cloud.gateway.server.webflux.routes[2].uri=lb://PROPERTYSERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/property/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=StripPrefix=1

# Reactive app
spring.main.web-application-type=reactive