spring.application.name=BookingService
server.port=9092



# Eureka config
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8080/eureka/

spring.datasource.url=jdbc:postgresql://34.29.38.248:5432/bookingservice
spring.datasource.username=postgres
spring.datasource.password=#SubbuSSRR@dugMY2

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true